version: "2"

services:  
  client:
    build:
      context: ./client
    ports:
      - "5000:5000"
    environment:
      - PRODUCER_SERVERS=kafka-broker:9092
      - CONSUMER_SERVERS=kafka-broker:9092
    restart: always
    networks:
      - multiuavfogverse
  
  executor:
    build:
      context: ./executor
    ports:
      - "5001:5001"
    environment:
      - PRODUCER_SERVERS=kafka-broker:9092
      - CONSUMER_SERVERS=kafka-broker:9092
    restart: always
    networks:
      - multiuavfogverse
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true
  
networks:
  multiuavfogverse:
    external: true
